name: 'My Custom Action'
description: 'A simple custom action example'
author: 'Your Name'
inputs:
  name:
    description: 'Your name'
    required: true
    default: 'World'
outputs:
  greeting:
    description: 'The greeting message'
runs:
  using: 'node12'
  main: 'index.js'
